AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  download-td

  Sample SAM Template for download-td

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:
  DownloadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: download_td/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Policies:
      - S3FullAccessPolicy:
          BucketName: demo-i

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  DownloadFunction:
    Description: Download Lambda Function ARN
    Value: !GetAtt DownloadFunction.Arn
  DownloadFunctionIamRole:
    Description: Implicit IAM Role created for Donwload function
    Value: !GetAtt DownloadFunctionRole.Arn
